# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import idm_suspension.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspended', idm_suspension.models.FSMBooleanField(default=False)),
                ('suspended_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
